is_rotated = {
    'mqxfa.b3l1': False,
    'mqxfa.a3l1': True,
    'mqxfb.b2l1': True,
    'mqxfb.a2l1': False,
    'mqxfa.b1l1': False,
    'mqxfa.a1l1': True,
    'mqxfa.a1r1': False,
    'mqxfa.b1r1': True,
    'mqxfb.a2r1': True,
    'mqxfb.b2r1': False,
    'mqxfa.a3r1': False,
    'mqxfa.b3r1': True,
    'mqxfa.b3l5': False,
    'mqxfa.a3l5': True,
    'mqxfb.b2l5': True,
    'mqxfb.a2l5': False,
    'mqxfa.b1l5': False,
    'mqxfa.a1l5': True,
    'mqxfa.a1r5': False,
    'mqxfa.b1r5': True,
    'mqxfb.a2r5': True,
    'mqxfb.b2r5': False,
    'mqxfa.a3r5': False,
    'mqxfa.b3r5': True,
    'mbxf.4l1': False,
    'mbxf.4r1': True,
    'mbxf.4l5': False,
    'mbxf.4r5': True,

    'mbrd.4l1': True,
    'mbrd.4r1': False,
    'mbrd.4l5': True,
    'mbrd.4r5': False,

    # never used, to be checked
    # 'mcbrdh.4l1': False,
    # 'mcbrdv.4l1': True,
    # 'mcbrdv.4r1': False,
    # 'mcbrdh.4r1': True,
    # 'mcbrdh.4l5': False,
    # 'mcbrdv.4l5': True,
    # 'mcbrdv.4r5': False,
    # 'mcbrdh.4r5': True
}
