
kLMCSmax=0.471*2 /0.017**2*0.3/7000.
kLMCOmax=0.040*6 /0.017**3*0.3/7000.
kLMCDmax=0.100*24/0.017**4*0.3/7000.


corrector_limits = {
    'kcs.a12b1':  (-kLMCSmax, kLMCSmax),
    'kcs.a23b1':  (-kLMCSmax, kLMCSmax),
    'kcs.a34b1':  (-kLMCSmax, kLMCSmax),
    'kcs.a45b1':  (-kLMCSmax, kLMCSmax),
    'kcs.a56b1':  (-kLMCSmax, kLMCSmax),
    'kcs.a67b1':  (-kLMCSmax, kLMCSmax),
    'kcs.a78b1':  (-kLMCSmax, kLMCSmax),
    'kcs.a81b1':  (-kLMCSmax, kLMCSmax),
    'kcs.a12b2':  (-kLMCSmax, kLMCSmax),
    'kcs.a23b2':  (-kLMCSmax, kLMCSmax),
    'kcs.a34b2':  (-kLMCSmax, kLMCSmax),
    'kcs.a45b2':  (-kLMCSmax, kLMCSmax),
    'kcs.a56b2':  (-kLMCSmax, kLMCSmax),
    'kcs.a67b2':  (-kLMCSmax, kLMCSmax),
    'kcs.a78b2':  (-kLMCSmax, kLMCSmax),
    'kcs.a81b2':  (-kLMCSmax, kLMCSmax),
    'kco.a12b1':  (-kLMCOmax, kLMCOmax),
    'kco.a23b1':  (-kLMCOmax, kLMCOmax),
    'kco.a34b1':  (-kLMCOmax, kLMCOmax),
    'kco.a45b1':  (-kLMCOmax, kLMCOmax),
    'kco.a56b1':  (-kLMCOmax, kLMCOmax),
    'kco.a67b1':  (-kLMCOmax, kLMCOmax),
    'kco.a78b1':  (-kLMCOmax, kLMCOmax),
    'kco.a81b1':  (-kLMCOmax, kLMCOmax),
    'kco.a12b2':  (-kLMCOmax, kLMCOmax),
    'kco.a23b2':  (-kLMCOmax, kLMCOmax),
    'kco.a34b2':  (-kLMCOmax, kLMCOmax),
    'kco.a45b2':  (-kLMCOmax, kLMCOmax),
    'kco.a56b2':  (-kLMCOmax, kLMCOmax),
    'kco.a67b2':  (-kLMCOmax, kLMCOmax),
    'kco.a78b2':  (-kLMCOmax, kLMCOmax),
    'kco.a81b2':  (-kLMCOmax, kLMCOmax),
    'kcd.a12b1':  (-kLMCDmax, kLMCDmax),
    'kcd.a23b1':  (-kLMCDmax, kLMCDmax),
    'kcd.a34b1':  (-kLMCDmax, kLMCDmax),
    'kcd.a45b1':  (-kLMCDmax, kLMCDmax),
    'kcd.a56b1':  (-kLMCDmax, kLMCDmax),
    'kcd.a67b1':  (-kLMCDmax, kLMCDmax),
    'kcd.a78b1':  (-kLMCDmax, kLMCDmax),
    'kcd.a81b1':  (-kLMCDmax, kLMCDmax),
    'kcd.a12b2':  (-kLMCDmax, kLMCDmax),
    'kcd.a23b2':  (-kLMCDmax, kLMCDmax),
    'kcd.a34b2':  (-kLMCDmax, kLMCDmax),
    'kcd.a45b2':  (-kLMCDmax, kLMCDmax),
    'kcd.a56b2':  (-kLMCDmax, kLMCDmax),
    'kcd.a67b2':  (-kLMCDmax, kLMCDmax),
    'kcd.a78b2':  (-kLMCDmax, kLMCDmax),
    'kcd.a81b2':  (-kLMCDmax, kLMCDmax),
}